// UI actions
export const TOGGLE_SIDE_DRAWER = 'TOGGLE_SIDE_DRAWER';

// Fetch users list actions
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';


// Auth actions
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';


// Conversations actions
export const CONTACT_SELECTED_SUCCESS = 'CONTACT_SELECTED_SUCCESS';
export const CONTACT_SELECTED_FAIL = 'CONTACT_SELECTED_FAIL';
export const FETCH_NEW_MESSAGE = 'FETCH_NEW_MESSAGE';
export const ADD_CONVERSATION_TO_LIST = 'ADD_CONVERSATION_TO_LIST';
export const FETCH_CONVERSATIONS_LIST_FAIL = 'FETCH_CONVERSATIONS_LIST_FAIL';
export const CLEAR_MESSAGES_LIST = 'CLEAR_MESSAGES_LIST'
export const ADD_MESSAGES_TO_LIST = 'ADD_MESSAGES_TO_LIST';

// Fetch current logged in user actions
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';


// Websocket and stomp actions
export const ON_CONNECT_SUCCESS = 'ON_CONNECT_SUCCESS';
export const ON_CONNECT_FAIL = 'ON_CONNECT_FAIL';
export const ON_SUBSCRIBE_SUCCESS = 'ON_SUBSCRIBE_SUCCESS';
export const ON_SUBSCRIBE_FAIL = 'ON_SUBSCRIBE_FAIL';
export const ON_UNSUBSCRIBE_SUCCESS = 'ON_UNSUBSCRIBE_SUCCESS';
export const ON_UNSUBSCRIBE_FAIL = 'ON_UNSUBSCRIBE_FAIL';